'use strict';
class ArcadeSound {
  constructor(){this.context=null;this.master=null;this.muted=false;this.voices=new Set();this.pendingResume=null;this.unavailable=false;this.effects={playerShot:{type:'square',from:900,to:260,duration:.07,gain:.10},playerHit:{type:'sawtooth',from:140,to:45,duration:.18,gain:.14},enemyShot:{type:'triangle',from:300,to:620,duration:.10,gain:.16},enemyDestroyed:{type:'sawtooth',from:480,to:55,duration:.24,gain:.12}};}
  unlock(){if(this.muted||this.unavailable)return;try{if(!this.context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){this.unavailable=true;return;}this.context=new Audio();this.master=this.context.createGain();this.master.gain.value=.22;this.master.connect(this.context.destination);}if(this.context.state==='suspended'&&!this.pendingResume){this.pendingResume=Promise.resolve(this.context.resume()).catch(()=>{}).finally(()=>{this.pendingResume=null;});}}catch{this.unavailable=true;this.stopAll();}}
  dispose(voice){if(!this.voices.delete(voice))return;voice.osc.onended=null;try{voice.osc.disconnect();voice.gain.disconnect();}catch{}}
  stopVoice(voice){try{voice.osc.stop();}catch{}this.dispose(voice);}
  stopAll(){for(const voice of [...this.voices])this.stopVoice(voice);}
  setMuted(muted){this.muted=muted;if(this.master)this.master.gain.value=muted?0:.22;if(muted)this.stopAll();else this.unlock();}
  play(name){if(this.muted||!this.context||this.context.state!=='running'||!this.effects[name])return;let voice;try{if(this.voices.size>=8)this.stopVoice(this.voices.values().next().value);const effect=this.effects[name],now=this.context.currentTime,osc=this.context.createOscillator(),gain=this.context.createGain();voice={osc,gain};this.voices.add(voice);osc.type=effect.type;osc.frequency.setValueAtTime(effect.from,now);osc.frequency.exponentialRampToValueAtTime(effect.to,now+effect.duration);gain.gain.setValueAtTime(.0001,now);gain.gain.linearRampToValueAtTime(effect.gain,now+.004);gain.gain.exponentialRampToValueAtTime(.0001,now+effect.duration);osc.connect(gain);gain.connect(this.master);osc.onended=()=>this.dispose(voice);osc.start(now);osc.stop(now+effect.duration+.01);}catch{if(voice)this.stopVoice(voice);}}
}
class SpaceAttackGame {
  constructor(canvas) {
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.keys=new Set();this.state='ready';this.score=0;this.wave=1;this.health=100;this.enemies=[];this.shots=[];this.hostile=[];this.particles=[];this.player={x:0,y:0,r:14};this.time=0;this.cooldown=0;this.invulnerable=0;this.banner=0;this.waveDelay=0;this.stars=Array.from({length:100},()=>({x:Math.random(),y:Math.random(),z:Math.random()}));this.resize();
    this.sound=new ArcadeSound();this.soundButton=document.getElementById('sound-toggle');this.soundButton.addEventListener('click',()=>this.toggleSound());this.soundHUD();
    window.addEventListener('resize',()=>this.resize());
    window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(e.target?.closest?.('button')&&[' ','enter'].includes(key))return;if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d'].includes(key)){e.preventDefault();if(this.state==='playing')this.keys.add(key);}if(!e.repeat&&key==='enter'){e.preventDefault();if(this.state==='ready'||this.state==='over')this.start();else if(this.state==='paused')this.resume();}if(!e.repeat&&key==='p'){if(this.state==='playing')this.pause();else if(this.state==='paused')this.resume();}if(!e.repeat&&key==='m'){e.preventDefault();this.toggleSound();}});
    window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>this.pause());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause();});document.getElementById('action').addEventListener('click',()=>{if(this.state==='paused')this.resume();else if(this.state==='ready'||this.state==='over')this.start();});
    this.last=performance.now();const frame=now=>{const dt=Math.min(.04,Math.max(0,(now-this.last)/1000));this.last=now;if(this.state==='playing')this.update(dt);this.draw();requestAnimationFrame(frame);};requestAnimationFrame(frame);this.hud();
  }
  resize(){const b=this.canvas.getBoundingClientRect();this.w=b.width;this.h=b.height;const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);this.player.x=Math.max(20,Math.min(this.w-20,this.player.x||this.w/2));this.player.y=this.h-85;for(const e of this.enemies){this.positionHome(e);this.positionEnemy(e);}for(const bullet of this.hostile)bullet.x=Math.max(0,Math.min(this.w,bullet.x));}
  soundHUD(){this.soundButton.textContent=this.sound.muted?'SOUND OFF':'SOUND ON';this.soundButton.setAttribute('aria-pressed',String(!this.sound.muted));this.soundButton.setAttribute('aria-label',this.sound.muted?'Enable sound (M)':'Mute sound (M)');}
  toggleSound(){this.sound.setMuted(!this.sound.muted);this.soundHUD();}
  start(){this.sound.stopAll();this.sound.unlock();this.keys.clear();this.score=0;this.wave=1;this.health=100;this.enemies=[];this.shots=[];this.hostile=[];this.particles=[];this.time=0;this.cooldown=0;this.invulnerable=0;this.waveDelay=0;this.player={x:this.w/2,y:this.h-85,r:14};this.state='playing';document.getElementById('overlay').classList.add('hidden');this.spawnWave();this.hud();}
  difficulty(){return{count:Math.min(24,7+this.wave*2),speed:100+12*this.wave,fireInterval:Math.max(.45,1.7-this.wave*.09),diveInterval:.85,maxDivers:3};}
  positionHome(e){const cols=Math.min(8,this.difficulty().count);e.homeX=80+(e.slot%cols)*(this.w-160)/Math.max(1,cols-1);e.homeY=120+Math.floor(e.slot/cols)*48;}
  positionEnemy(e){if(e.mode==='diving'){e.y=e.homeY+e.progress*(this.h+25-e.homeY);const amplitude=Math.max(0,Math.min(75,e.homeX-20,this.w-20-e.homeX));e.x=e.homeX+Math.sin(e.progress*Math.PI*3)*amplitude;}else{e.x=e.homeX;e.y=e.homeY;}}
  spawnWave(){const d=this.difficulty();this.banner=2;this.diveTimer=1.3;this.nextSlot=0;for(let i=0;i<d.count;i++){const e={slot:i,mode:'formation',progress:0,r:16,hp:1,fire:.35,color:i%3===0?'#ffb65e':'#ff618f'};this.positionHome(e);this.positionEnemy(e);this.enemies.push(e);}this.hud();}
  scheduleDive(){const candidates=this.enemies.filter(e=>!e.dead&&e.mode==='formation').sort((a,b)=>a.slot-b.slot);if(!candidates.length)return;const e=candidates.find(e=>e.slot>=this.nextSlot)||candidates[0];this.nextSlot=(e.slot+1)%this.difficulty().count;e.mode='diving';e.progress=0;e.fire=.35;}
  pause(){this.keys.clear();this.sound.stopAll();if(this.state!=='playing')return;this.state='paused';this.showOverlay('MISSION PAUSED','PAUSED','Your ship is safe. Return when you’re ready.','RESUME MISSION','PRESS ENTER OR P TO RESUME');}
  resume(){this.sound.unlock();this.keys.clear();this.state='playing';this.last=performance.now();document.getElementById('overlay').classList.add('hidden');}
  showOverlay(eyebrow,title,message,action,hint){document.getElementById('eyebrow').textContent=eyebrow;document.getElementById('title').textContent=title;document.getElementById('message').textContent=message;document.getElementById('action').textContent=action+' ↗';document.getElementById('hint').textContent=hint;document.getElementById('overlay').classList.remove('hidden');}
  damage(){if(this.invulnerable>0||this.state!=='playing')return;this.health=Math.max(0,this.health-20);this.sound.play('playerHit');this.invulnerable=1.1;this.burst(this.player.x,this.player.y,'#64ffd6',16);this.hud();if(this.health===0){this.state='over';this.sound.stopAll();this.keys.clear();this.showOverlay('MISSION COMPLETE · WAVE '+this.wave,'GAME OVER','Final score: '+String(this.score).padStart(6,'0')+' · The frontier awaits your return.','TRY AGAIN','PRESS ENTER TO RESTART');}}
  burst(x,y,color,count=10){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=30+Math.random()*110;this.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.5+Math.random()*.3,color});}}
  update(dt){if(this.state!=='playing')return;dt=Math.min(.04,Math.max(0,dt));this.time+=dt;this.cooldown-=dt;this.invulnerable=Math.max(0,this.invulnerable-dt);this.banner=Math.max(0,this.banner-dt);const dx=(this.keys.has('d')||this.keys.has('arrowright')?1:0)-(this.keys.has('a')||this.keys.has('arrowleft')?1:0);this.player.x=Math.max(20,Math.min(this.w-20,this.player.x+dx*300*dt));this.player.y=this.h-85;if(this.keys.has(' ')&&this.cooldown<=0){this.shots.push({x:this.player.x,y:this.player.y-20,r:4});this.sound.play('playerShot');this.cooldown=.15;}
    for(const s of this.shots)s.y-=620*dt;for(const b of this.hostile){b.y+=b.vy*dt;b.x+=b.vx*dt;}const d=this.difficulty();this.diveTimer-=dt;if(this.diveTimer<=0&&this.enemies.filter(e=>e.mode==='diving'&&!e.dead).length<d.maxDivers){this.scheduleDive();this.diveTimer=d.diveInterval;}
    for(const e of this.enemies){if(e.mode!=='diving')continue;e.progress+=d.speed*dt/(this.h+25-e.homeY);if(e.progress>=1){e.mode='formation';e.progress=0;e.fire=.35;this.positionEnemy(e);continue;}this.positionEnemy(e);e.fire-=dt;if(e.y<this.h&&e.fire<=0){const angle=Math.atan2(this.player.y-e.y,this.player.x-e.x);const speed=140+Math.min(this.wave*8,100);this.hostile.push({x:e.x,y:e.y,r:5,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed});this.sound.play('enemyShot');e.fire=d.fireInterval+Math.random()*.6;}}
    for(const s of this.shots){if(s.dead)continue;for(const e of this.enemies){if(e.dead)continue;if(Math.hypot(s.x-e.x,s.y-e.y)<s.r+e.r){s.dead=true;e.dead=true;this.sound.play('enemyDestroyed');this.score+=100;this.burst(e.x,e.y,e.color);this.hud();break;}}}for(const b of this.hostile){if(Math.hypot(b.x-this.player.x,b.y-this.player.y)<b.r+this.player.r){b.dead=true;this.damage();}}for(const e of this.enemies){if(!e.dead&&Math.hypot(e.x-this.player.x,e.y-this.player.y)<e.r+this.player.r){e.dead=true;if(this.state==='playing')this.sound.play('enemyDestroyed');this.burst(e.x,e.y,e.color);this.damage();}}
    this.shots=this.shots.filter(s=>!s.dead&&s.y>-20);this.hostile=this.hostile.filter(b=>!b.dead&&b.y<this.h+20&&b.y>-20&&b.x>-20&&b.x<this.w+20);this.enemies=this.enemies.filter(e=>!e.dead);for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}this.particles=this.particles.filter(p=>p.life>0);if(this.state==='playing'&&this.enemies.length===0){this.waveDelay+=dt;if(this.waveDelay>.9){this.wave++;this.health=100;this.waveDelay=0;this.hostile=[];this.spawnWave();}}else this.waveDelay=0;
  }
  hud(){document.getElementById('score').textContent=String(this.score).padStart(6,'0');document.getElementById('wave').textContent=String(this.wave).padStart(2,'0');document.getElementById('health').textContent=this.health+'%';document.getElementById('health-fill').style.width=this.health+'%';document.getElementById('health-fill').style.background=this.health<=40?'#ff618f':'#64ffd6';}
  ship(x,y,color,enemy=false){const c=this.ctx;c.save();c.translate(x,y);c.fillStyle=color;c.shadowColor=color;c.shadowBlur=12;c.beginPath();if(enemy){c.moveTo(0,13);c.lineTo(-16,-7);c.lineTo(-10,-13);c.lineTo(0,-5);c.lineTo(10,-13);c.lineTo(16,-7);}else{c.moveTo(0,-20);c.lineTo(17,14);c.lineTo(6,9);c.lineTo(0,14);c.lineTo(-6,9);c.lineTo(-17,14);}c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#081322';c.fillRect(-3,enemy?-5:-7,6,10);if(!enemy){c.fillStyle='#d6fff7';c.fillRect(-3,15,6,8+Math.sin(this.time*40)*3);}c.restore();}
  draw(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#080f1c';c.fillRect(0,0,this.w,this.h);const glow=c.createRadialGradient(this.w*.5,this.h*.45,0,this.w*.5,this.h*.45,this.w*.6);glow.addColorStop(0,'#16304955');glow.addColorStop(1,'#080f1c00');c.fillStyle=glow;c.fillRect(0,0,this.w,this.h);c.strokeStyle='#20314b33';c.lineWidth=1;for(let x=0;x<this.w;x+=70){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h);c.stroke();}for(const s of this.stars){c.fillStyle=`rgba(160,209,241,${.2+s.z*.6})`;c.fillRect(s.x*this.w,(s.y*this.h+this.time*(9+s.z*20))%this.h,1+s.z,1+s.z);}for(const e of this.enemies)this.ship(e.x,e.y,e.color,true);for(const s of this.shots){c.fillStyle='#9affeb';c.shadowColor='#64ffd6';c.shadowBlur=14;c.fillRect(s.x-2,s.y-9,4,16);}c.shadowBlur=0;for(const b of this.hostile){c.fillStyle='#ff779a';c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.fill();}for(const p of this.particles){c.globalAlpha=Math.min(1,p.life*2);c.fillStyle=p.color;c.fillRect(p.x,p.y,3,3);}c.globalAlpha=1;if(this.state!=='over'&&(this.invulnerable<=0||Math.floor(this.time*15)%2===0))this.ship(this.player.x,this.player.y,'#64ffd6');if(this.invulnerable>.85){c.fillStyle='#ff618f16';c.fillRect(0,0,this.w,this.h);}document.getElementById('wave-banner').textContent=this.state==='playing'&&this.banner>0?'WAVE '+String(this.wave).padStart(2,'0')+' / INCOMING':'';}
  snapshot(){return{state:this.state,score:this.score,wave:this.wave,health:this.health,player:{...this.player},enemies:this.enemies.length,divers:this.enemies.filter(e=>e.mode==='diving').length,diveTimer:this.diveTimer,nextSlot:this.nextSlot,shots:this.shots.length,hostile:this.hostile.length,particles:this.particles.length,difficulty:this.difficulty()};}
}
window.spaceAttack=new SpaceAttackGame(document.getElementById('game'));


