const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'..','game','game.js'),'utf8');
function load(Audio){const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,{style:{},classList:{add(){},remove(){}},addEventListener(){},setAttribute(){}});return nodes.get(id);};nodes.set('game',{getContext:()=>({setTransform(){}}),getBoundingClientRect:()=>({width:1100,height:700})});const ctx={window:{AudioContext:Audio,addEventListener(){}},document:{getElementById:get,addEventListener(){}},performance:{now:()=>0},requestAnimationFrame(){},Math,Set,Promise};vm.createContext(ctx);vm.runInContext(source,ctx);return{g:ctx.window.spaceAttack,nodes};}
let created=0;const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});class FakeAudio{constructor(){created++;this.state='running';this.currentTime=0;this.destination={};}createGain(){return{gain:param(),connect(){},disconnect(){}};}createOscillator(){return{frequency:param(),connect(){},disconnect(){},start(){},stop(){}};}}
(async()=>{const {g,nodes}=load(FakeAudio);assert.equal(created,0);g.start();assert.equal(created,1);const emitted=[],original=g.sound.play.bind(g.sound);g.sound.play=name=>{emitted.push(name);original(name);};g.keys.add(' ');g.update(0);assert.deepEqual(emitted,['playerShot']);g.keys.clear();g.damage();g.damage();assert.equal(emitted.filter(n=>n==='playerHit').length,1);g.health=40;g.invulnerable=0;g.enemies=[{x:500,y:200,r:16,mode:'formation',color:'#fff'}];g.shots=[{x:500,y:200,r:4},{x:500,y:200,r:4}];g.update(0);assert.equal(emitted.filter(n=>n==='enemyDestroyed').length,1);const score=g.score;for(let i=0;i<24;i++)g.update(.04);assert.equal(g.wave,2);assert.equal(g.health,100);assert.equal(g.score,score);assert.equal(nodes.get('health-fill').style.width,'100%');assert.equal(nodes.get('health-fill').style.background,'#64ffd6');g.health=60;g.pause();g.resume();g.update(.04);assert.equal(g.health,60);
const e=g.enemies[0];e.mode='diving';e.progress=.2;e.fire=0;g.update(0);assert.equal(emitted.filter(n=>n==='enemyShot').length,1);const count=emitted.length;e.progress=1;g.update(0);assert.equal(emitted.length,count);assert.equal(g.health,60);g.enemies=[];g.waveDelay=.89;g.health=20;g.invulnerable=0;g.damage();g.update(.04);assert.equal(g.state,'over');assert.equal(g.health,0);assert.equal(g.wave,2);assert.equal(g.sound.voices.size,0);
for(let i=0;i<3;i++)g.start();assert.equal(created,1);for(let i=0;i<20;i++)original('playerShot');assert.equal(g.sound.voices.size,8);for(const v of [...g.sound.voices])v.osc.onended();assert.equal(g.sound.voices.size,0);original('playerShot');g.toggleSound();assert.equal(g.sound.voices.size,0);assert.equal(g.sound.master.gain.value,0);original('playerShot');assert.equal(g.sound.voices.size,0);g.start();assert.equal(g.sound.muted,true);g.toggleSound();original('playerShot');assert.equal(g.sound.voices.size,1);g.pause();assert.equal(g.sound.voices.size,0);
const unsupported=load().g;unsupported.start();unsupported.keys.add(' ');unsupported.update(.04);assert.equal(unsupported.shots.length,1);assert.equal(unsupported.sound.context,null);class Rejected extends FakeAudio{constructor(){super();this.state='suspended';}resume(){return Promise.reject(new Error('blocked'));}}const blocked=load(Rejected).g;blocked.start();await Promise.resolve();await Promise.resolve();blocked.keys.add(' ');blocked.update(.04);assert.equal(blocked.shots.length,1);assert.equal(blocked.sound.voices.size,0);
console.log('PASS SA003: genuine stage refill/HUD/score, no return/pause refill or lethal-delay resurrection, event mapping, one lazy context through three restarts, max8/finished cleanup, mute persistence/unmute/pause silence, unsupported/rejected-resume gameplay. Audio mocked; actual browser signal verification required.');})().catch(e=>{console.error(e);process.exitCode=1;});
