const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',style:{},classList:{add(){},remove(){}},addEventListener(){},setAttribute(){}});return elements.get(id);};
const canvas={getContext:()=>({setTransform(){}}),getBoundingClientRect:()=>({width:1100,height:700})};elements.set('game',canvas);
const context={window:{devicePixelRatio:1,addEventListener(){}},document:{getElementById:element,addEventListener(){}},performance:{now:()=>0},requestAnimationFrame(){},Math,Set};vm.createContext(context);vm.runInContext(fs.readFileSync('game.js','utf8'),context);const g=context.window.spaceAttack;
assert.equal(g.state,'ready');g.start();assert.equal(g.enemies.length,9);assert.equal(g.health,100);
g.keys.add('d');g.keys.add(' ');for(let i=0;i<25;i++)g.update(.04);assert(g.player.x>550);assert(g.shots.length<=7);assert(g.shots.length>=5);
g.keys.clear();g.score=0;g.enemies=[{x:500,y:200,r:16,fire:99,phase:0,color:'#fff'}];g.shots=[{x:500,y:200,r:4},{x:500,y:200,r:4}];g.update(0);assert.equal(g.score,100);assert.equal(g.enemies.length,0);
g.damage();assert.equal(g.health,80);g.damage();assert.equal(g.health,80);for(let i=0;i<4;i++){g.invulnerable=0;g.damage();}assert.equal(g.health,0);assert.equal(g.state,'over');
for(let i=0;i<3;i++){g.start();assert.equal(g.wave,1);assert.equal(g.score,0);assert.equal(g.health,100);assert.equal(g.shots.length,0);assert.equal(g.hostile.length,0);}
const first=g.difficulty();g.enemies=[];for(let i=0;i<24;i++)g.update(.04);assert.equal(g.wave,2);assert(g.difficulty().count>first.count);assert(g.difficulty().speed>first.speed);g.pause();assert.equal(g.state,'paused');assert.equal(g.keys.size,0);g.resume();assert.equal(g.state,'playing');
g.start();const baseline=g.player.y;const initialX=g.player.x;g.keys.add('d');g.keys.add('w');g.update(.04);assert.equal(g.player.y,baseline);assert.equal(g.player.x-initialX,12);g.keys.clear();for(const key of ['w','s','arrowup','arrowdown']){g.keys.add(key);g.update(.04);assert.equal(g.player.y,baseline);g.keys.clear();}
g.start();g.player.r=-1000;g.invulnerable=999;const seen=new Set();let returned=false;let lastPositions=new Map();for(let i=0;i<2000;i++){g.update(.04);assert(g.enemies.filter(e=>e.mode==='diving').length<=3);for(const e of g.enemies){if(e.mode==='diving')seen.add(e.slot);if(lastPositions.get(e.slot)==='diving'&&e.mode==='formation')returned=true;lastPositions.set(e.slot,e.mode);}assert.equal(g.enemies.length,9);assert.equal(g.wave,1);assert.equal(g.score,0);}assert.equal(seen.size,9);assert(returned);g.pause();const progress=g.enemies.map(e=>e.progress);g.update(.04);assert.deepEqual(g.enemies.map(e=>e.progress),progress);g.resume();
g.wave=20;const speed20=g.difficulty().speed;g.wave=21;assert(g.difficulty().speed>speed20);g.start();const diver=g.enemies[3];diver.mode='diving';diver.progress=.2;diver.fire=0;g.update(0);const bullet=g.hostile[0];const tx=g.player.x-diver.x,ty=g.player.y-diver.y;assert(Math.abs(bullet.vx*ty-bullet.vy*tx)<1e-6);assert(bullet.vx*tx+bullet.vy*ty>0);
g.keys.add('d');for(let i=0;i<200;i++)g.update(.04);assert(g.player.x<=g.w-20);
console.log('PASS: start, horizontal controls and vertical-key independence, firing cadence, single score collision, damage/immunity/death, three resets, wave scaling including 20->21, pause freeze/resume, bounds, nine-slot scheduler fairness, <=3 divers, survivor returns/count/score preservation, aimed fire vector. Mocked state checks; browser QA remains required.');
