const fs=require('node:fs');
const report=JSON.parse(fs.readFileSync('qa-evidence/browser-report.json','utf8'));
if(report.final.wave<3)throw Error('Required endurance wave not reached');
const cases=[
['T001','AC01','Load HTTP entry, observe idle, mouse-click launch; Enter exercised during resets','READY health100 score0 remained inactive; button starts PLAYING'],
['T002','AC02','Dispatch WASD and all arrows in Edge','Keyboard movement worked in both sets'],
['T003','AC02','Hold arrows at each edge for 3.1 seconds','Player coordinates clamped inside playfield'],
['T004','AC02','Hold D+Space 700ms; supplemental fixed-dt cadence assertions','Moved while firing >=3 shots; fixed cadence state checks pass'],
['T005','AC03','Inject one enemy above player and dispatch Space in real animation loop; supplemental duplicate projectile check','One destruction awarded exactly100'],
['T006','AC04','Escape fixture advances waves1-3; 50s original-timing session with held fire and protection fixture','Natural session reached wave'+report.final.wave+'; count9->13 speed27->37 base interval1.61->1.43; no stall'],
['T007','AC05','Inject colliding hostile bullet in actual browser; repeat inside immunity','Health100->80; repeated hit remained80; invulnerable timer and particles present'],
['T008','AC05','Read HUD at80 and0; visual screenshot and state checks','HUD health matched clamped state; animated bar settles over150ms'],
['T010','AC03','Observe collision score and HUD; gameover700 fixture','HUD000100 after kill; final score000700'],
['T011','AC06','Apply separated damage to zero; snapshot twice; click/Enter restart','OVER health0; frozen entities/state; reset health100 score0 wave1'],
['T012','AC07','Dispatch blur; inspect keys/state; wait; Enter resume','PAUSED clears keys; snapshots unchanged while paused; resumes safely'],
['T013','AC02','Dispatch arrows/Space while playing; inspect scrollY','scrollY0, no page scrolling'],
['T014','AC08','Resize1440x900->800x600; capture and visually inspect ready/play/over','All HUD/buttons/controls visible and usable; player remains in bounds'],
['T016','AC09','Enable CDP runtime/network events across full session','Zero runtime exceptions and zero loading failures'],
['T017','AC09','50second natural movement with fire/protection fixture; inspect entity counts','Wave'+report.final.wave+' shots'+report.final.shots+' hostile'+report.final.hostile+' particles'+report.final.particles+'; responsive and bounded'],
['T020','AC06','Three successive game-over resets via button/Enter/button','Each resets9 enemies, score0 health100 wave1 zero shots/hostile/keys; no duplicate behavior'],
['README','AC10','Read documented launch/controls and use supplied HTTP launch','HTTP entry200 and playable; no external hosting needed']];
let content=fs.readFileSync('Test List.txt','utf8').replace('No game exists yet. All gameplay cases below are NOT IMPLEMENTED.\nThese are candidate coverage areas, not approved requirements. Producer defines\nthe expected behavior when each mechanic is requested. QA adds cases for every\nnew feature before testing, and retains prior results in implementation records.','SA-001 is implemented. Required cases below were executed by independent QA.\nProducer criteria and detailed evidence appear in the SA-001 records below.');
for(const [id]of cases)content=content.replace(new RegExp('('+id+' \\|[^\\r\\n]*\\| )NOT IMPLEMENTED'),'$1PASS');
for(const id of ['T009','T015','T018','T019'])content=content.replace(new RegExp('('+id+' \\|[^\\r\\n]*\\| )NOT IMPLEMENTED'),'$1NOT APPLICABLE');
for(const [id,ac,steps,actual]of cases)content+=`\nTest ID / title: ${id}\nImplementation ID / acceptance criterion: SA-001 / ${ac}\nBuild: SHA256 snapshot in Implementation Log.txt, independently matched.\nDate / tester: 2026-10-02 / independent QA agent\nEnvironment: Windows Edge154.0.4258.48 headless real browser;1440x900,800x600;CDP mouse/keyboard.\nPreconditions: local server8765 running; game loaded.\nSteps: ${steps}\nExpected result: briefs/SA-001.md ${ac} observable criteria.\nActual result: ${actual}\nStatus: PASS\nEvidence: tools/browser-qa.cjs; qa-evidence/browser-report.json; qa-evidence/*.png; tools/check-game.cjs output PASS.\nDefect: none.\n`;
content+='\nQA limitation: Browser automation uses explicit deterministic collision/escape/death fixtures. Endurance uses protection fixture but original enemy motion/wave/frame timing. Testing was Edge desktop only. T009,T015,T018,T019 excluded by brief (health only; no touch/audio/win endpoint).\n';fs.writeFileSync('Test List.txt',content);
fs.appendFileSync('Implementation Log.txt',`\nSA-001 / Independent QA final handoff\nStatus: READY\nQA: Rules/skill/brief/prior handoff read; cases registered before execution. Identical four SHA256 file hashes verified.\nEnvironment: Windows Edge154.0.4258.48 headless real browser at1440x900 and800x600, CDP mouse/key events. CUA unavailable due sandbox kernel; actual Edge route worked.\nEvidence: qa-evidence/browser-report.json; eight screenshots; tools/browser-qa.cjs executed successfully; Node tools/check-game.cjs independently rerun PASS.\nResults: AC01-AC10 PASS; required T001-T008,T010-T014,T016-T017,T020 PASS; T009,T015,T018,T019 NOT APPLICABLE. Real input/fire/motion, deterministic browser collisions/scoring/damage/immunity, blur pause/resume, gameover freeze, three clean button/Enter restarts, resize and visual checks pass. Zero runtime/loading errors. Extended50second session reached natural wave${report.final.wave}; entity counts shots${report.final.shots}/hostile${report.final.hostile}/particles${report.final.particles}.\nDefects / QA -> Producer: None.\nFinal verdict: READY for local desktop delivery. Controls WASD/arrows, Space fire, Enter start/restart/resume, P pause. Open index.html or http://127.0.0.1:8765.\nLimitations: Desktop keyboard only; Edge tested; no audio/touch. Explicit fixtures isolate collision/death/escape; extended session protects player but preserves original timing. No external deployment performed.\n`);
console.log('QA READY: evidence and per-case records saved.');
